# Quantifying Uncertainty in Forest Ecosystem Service Valuation

## Introduction

There is a need to accurately quantify the economic and social benefits that ecosystems provide.  First, this is required in order to understand the costs of compromising ecosystem structure and function, and thereby to rigorously price ecosystem losses and degradation into the economy. Second, it is necessary to design and finance incentives for managing ecosystems for resilience, restoration, and protection. It is well understood, for example, that forests provide a host of benefits to society, including a supply of wood products, wildlife habitat, water quality, and carbon sequestration. Conventional forest products such as lumber and fiber are typically the only ecosystem products and services that are rigorously quantified and valued in the economy, however. This is due both to their importance in the material economy, and also due to their relative ease to measure and value. Managing for a single value stream that forests provide can lead to imbalanced management, however, that comes at the cost of ignoring products and services that are less easy to quantify but of no less importance to society. Ignoring the non-wood ecosystem services that forests provide therefore leads to underestimating the social costs of forest ecosystem degradation and loss.

Because of this need, efforts to quantify and trade other ecosystem services outside typical commodities markets have been developing and growing over the past 30 years. For example, the voluntary carbon market (VCM) conducted $XXM of trade in 2022, YY% of which was forest carbon. Given the immediate promise of managing forests for carbon sequestration and storage in order to help society meet climate change mitigation targets, it is expected that demand for offsets from forest carbon projects will continue to rise, and there are similar efforts under way to develop similar trading mechanisms for both wildlife habitat and water quality and delivery. The hope for such markets is that they will be efficient in funneling capital to fund ecosystem protection and restoration. Even after twenty years, however, all such markets and trading mechanisms still face significant hurdles in their implementation. Unfortunately, carbon markets are today plagued by fundamental questions of quality, and the efficacy of carbon projects in creating true climate-positive offsets is doubtful. Each year there is a new parade of journalistic and scientific publications calling into question the real benefits that forest carbon projects provide in terms of climate change mitigation, with some estimating that 90% or more of all carbon projects could be mostly if not fully non-additional. Thus while functional ecosystem services markets could in theory be a valuable tool for allocating capital and incentivizing management of forests for goods and services other than wood, in practice their true efficacy as currently realized is doubtful.

Part of the challenge to developing robust markets for ecosystem services from forests outside conventional commodities stems from problems related to measurement and modeling. While a whole science of forest biometrics has developed around the quantification of growth and yield of wood products, for example, the field of quantifying other ecosystem services from forests is comparatively young. Moreover, the fields of ecosystem service quantification and conventional forest biometrics are somewhat split, both culturally and methodologically. Conventional forest biometrics has traditionally focused on design-based field sampling and using unbiased estimation techniques to develop point estimates of growth and yield. This is partly due to the history of forestry and its close affiliation with classical statistical techniques and the development of sampling theory in the 20th century. It is fairly straightforward to develop sampling designs and field measurement protocols to quantify stocking, and to develop fairly simple models of growth to project future yield. This is especially true in intensive, relatively homogenous management scenarios such as plantations. Most of the value that is being measured is straightforward to quantify with conventional sampling designs focusing on measuring bole diameter.

By contrast, ecosystem services such as habitat suitability, carbon sequestration and storage, and water quality and delivery quantity are not static values that can be reduced to simple dimensions of measurement. Because these services are themselves functions of complex ecological structural and process dynamics, often with high variation over space and time, rigorously quantifying these values requires much more sophisticated measurement and modeling efforts. For example, accurately measuring the amount of terrestrial carbon stored on a sample plot would, in theory, require a full accounting of mineral soil carbon, litter layer carbon, downed woody debris, and live and dead aboveground biomass. Directly computing these quantites for even a small field plot is not really feasible, and certainly a quantification strategy that required direct measurement of all these pools is not scalable. Instead, such values must be estimated using statistical and machine learning models that.

Building on the traditions of forest mensuration, one strategy that has been employed in ecosystem service valuation is to combine design-based point estimates from many independent sub-models within a larger, often simple value model. For example, a conventional forest carbon project might conduct sample-measurements and build design-based estimates of each carbon pool deemed relevant for the project and then combined additively to develop estimates of current carbon stocks, baseline scenarios, and project impact. Such approaches face several problems. First, some important component models that contribute to value can be left out, overly simplified, or poorly estimated. Second, when such strategies often do not correctly represent the dependency structure that can exist between submodels. Third, when point estimates from several models are linked, the information regarding the uncertainty of each component submodel is lost.

In theory, what is required for trustworthy ecosystem service valuation and marketplace is 1) the definition of rigorous metrics of value that buyers and sellers are willing to trade (e.g. carbon emissions for climate impact) that are linked to economic and ecosystem structure and process; 2) the development of sufficiently rich probablistic models of ecosystem function and process that allow for prediction of the value metric across the plausible range of management, natural disturbance, and climate scenarios, and 3) methods to translate probablistic delivery of ecosystem service value into project financing and tradeable assets.

## Methods

We demonstrate the development of probablistic models of ecosystem service delivery linked to ecological structure and process. This is accomplished by building a spatiotemporal model of forest composition and structure for New England (Maine?).

- Land cover model: forest / agriculture / hardscape
  Inputs:
    - existing land cover layers (e.g. copernicus, NLCD)
    - climate (WorldClim)
    - soil
    - remote sensing
      - multispectral
      - SAR
  Output:
    - land cover class
    
- Forest type model: spruce-fir, hardwood
    - conditional on land cover classification
    -

- Forest structural model: tree counts by species and diameter
- Climate impact model: integrate emissions under differing management scenarios

## Connection to NEFF needs

We develop a simple model of:

- 

# Spatiotemporal Uncertainty in Ecosystem Service Valuation

## Introduction



## Methods

# Chapter Three: Uncertainty Under Differing Management and Climate Assumptions

## Introduction

## Methods

# Managing Under Uncertainty: A Decision Theoretic Approach to Forest Management

## Introduction

## Methods

